

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Check for code changes
        if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'code')
        run: echo 'Code changes found'

      - name: Enforce code coverage report
        if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'code')
        run: npm run coverage

      - name: Verify code linting and unit tests
        if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'code')
        run: npm run lint && npm test

      - name: Complete job
        if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'code')
        run: echo 'Job completed successfully'