

name: branch-protection.yml

on:
  push:
    branches: [main]

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '\.js$'
      - name: Enforce code coverage report
        if: ${{ steps.check-code-changes.outputs.code-changes == 'true' }}
        run: npm run code-coverage
      - name: Verify code linting and unit tests
        if: ${{ steps.check-code-changes.outputs.code-changes == 'true' }}
        run: npm run lint && npm run test
      - name: Complete job
        if: ${{ steps.check-code-changes.outputs.code-changes == 'true' }}
        run: echo "Job completed successfully."